"""Inbound message classification.

The rule this module exists to get right: **an auto-reply must not stop a sequence, and
a human reply must.** Both arrive as "a message came back". Treating an out-of-office
as a reply silently drops a live prospect who was on holiday; treating a human reply as
noise sends them step 3 after they already answered. The first loses a deal quietly,
the second is the single worst thing this system can do.

So detection runs headers-first and only falls back to text. Headers are what senders
actually set to say "this was generated by a machine" - RFC 3834's Auto-Submitted, the
null Return-Path, RFC 3464 delivery-status reports. Subject-line matching is a last
resort because "Out of office" is also a thing a person types.

Everything here is deterministic and free. An LLM pass can refine *intent* among human
replies (positive / objection / referral), but it must never be what decides whether a
message was machine-generated - that decision gates a send.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from email.message import Message
from enum import Enum


class Kind(str, Enum):
    HUMAN_REPLY = "human_reply"
    AUTO_REPLY = "auto_reply"
    OUT_OF_OFFICE = "out_of_office"
    BOUNCE_HARD = "bounce_hard"
    BOUNCE_SOFT = "bounce_soft"
    UNSUBSCRIBE = "unsubscribe"
    UNKNOWN = "unknown"

    def __str__(self) -> str:
        return self.value


class Intent(str, Enum):
    POSITIVE = "positive"
    OBJECTION = "objection"
    REFERRAL = "referral"
    NEUTRAL = "neutral"

    def __str__(self) -> str:
        return self.value


#: Kinds that must stop the sequence for this contact.
STOPS_SEQUENCE = {Kind.HUMAN_REPLY, Kind.BOUNCE_HARD, Kind.UNSUBSCRIBE}
#: Kinds that must NOT stop it. An OOO means "try again later", not "no".
CONTINUES_SEQUENCE = {Kind.AUTO_REPLY, Kind.OUT_OF_OFFICE, Kind.BOUNCE_SOFT, Kind.UNKNOWN}
#: Kinds that add the address to suppression.
SUPPRESSES = {Kind.BOUNCE_HARD, Kind.UNSUBSCRIBE}

_DAEMONS = ("mailer-daemon", "postmaster", "mail delivery", "microsoftexchange",
            "no-reply", "noreply", "donotreply")

_OOO_SUBJECT = re.compile(
    r"\b(out of (the )?office|automatic repl(y|ies)|auto[- ]?reply|autoreply"
    r"|away from (my|the) (desk|office)|annual leave|on leave|on vacation|on holiday"
    r"|maternity leave|paternity leave|parental leave|abwesenheit|abwesend"
    r"|réponse automatique|absence du bureau|fuera de la oficina|ausencia)\b",
    re.I)

_UNSUB = re.compile(
    r"\b(unsubscribe|remove me|take me off|opt[- ]?out|stop (emailing|contacting|messaging)"
    r"|do not (contact|email) (me|us)|please stop)\b", re.I)

_POSITIVE = re.compile(
    r"\b(interested|sounds good|let'?s (talk|chat|do it|set)|happy to|book (a|some) time"
    r"|calendar|schedule a (call|chat|demo)|send (me )?(more|over)|tell me more"
    r"|works for me|keen|yes please)\b", re.I)

_OBJECTION = re.compile(
    r"\b(not interested|no thanks|no thank you|we'?re (all )?(set|good|sorted)"
    r"|already (have|use|using|working with)|not (a|the) right time|not right now"
    r"|no budget|too expensive|pass\b|not for us|wrong fit)\b", re.I)

_REFERRAL = re.compile(
    r"\b(not the right person|speak (to|with)|reach out to|you (should|want) (to )?(talk|speak|contact)"
    r"|copying in|cc'?ing|forwarded (this )?to|better person|colleague|my colleague"
    r"|handles (this|that)|owns (this|that))\b", re.I)

# RFC 3463 enhanced status: 5.x.x permanent, 4.x.x transient.
_ENHANCED = re.compile(r"\b([245])\.(\d{1,3})\.(\d{1,3})\b")
_SMTP_CODE = re.compile(r"\b([245]\d{2})\b")

_HARD_PHRASES = re.compile(
    r"(user unknown|no such user|does not exist|doesn'?t exist|unknown recipient"
    r"|recipient (address )?rejected|invalid recipient|mailbox (unavailable|not found)"
    r"|address not found|account (has been )?(disabled|closed|deactivated)"
    r"|no longer (with|employed|works)|permanent(ly)? fail)", re.I)

_SOFT_PHRASES = re.compile(
    r"(mailbox full|over quota|quota exceeded|temporar(y|ily)|try again later"
    r"|greylist|deferred|insufficient (storage|system storage)|service unavailable"
    r"|too many (messages|connections)|rate limit)", re.I)


@dataclass(slots=True)
class Classification:
    kind: Kind
    intent: Intent | None = None
    confidence: float = 1.0
    evidence: list[str] = field(default_factory=list)
    bounced_address: str | None = None

    @property
    def stops_sequence(self) -> bool:
        return self.kind in STOPS_SEQUENCE

    @property
    def suppresses(self) -> bool:
        return self.kind in SUPPRESSES


def _looks_ooo(subject: str, body: str) -> bool:
    """Most vacation responders put the wording in the body ("I am on annual leave")
    and leave the subject as a plain "Re: ...". Checking only the subject misclassified
    those as a generic auto-reply, which cost them their 5-day retry."""
    return bool(_OOO_SUBJECT.search(subject) or _OOO_SUBJECT.search(body[:1200]))


def _h(msg: Message, name: str) -> str:
    return (msg.get(name) or "").strip()


def _body_text(msg: Message, limit: int = 8000) -> str:
    if not msg.is_multipart():
        try:
            return (msg.get_payload(decode=True) or b"").decode(errors="replace")[:limit]
        except (AttributeError, LookupError):
            return str(msg.get_payload())[:limit]
    parts = []
    for part in msg.walk():
        if part.get_content_type() == "text/plain":
            try:
                parts.append((part.get_payload(decode=True) or b"").decode(errors="replace"))
            except (AttributeError, LookupError):
                continue
    return "\n".join(parts)[:limit]


def _is_dsn(msg: Message) -> bool:
    ctype = (msg.get_content_type() or "").lower()
    if ctype == "multipart/report":
        return "delivery-status" in (msg.get_param("report-type") or "").lower()
    return any(p.get_content_type() == "message/delivery-status" for p in msg.walk())


def _dsn_status(msg: Message) -> tuple[str | None, str | None]:
    """Returns (enhanced status, failed recipient) from the delivery-status part."""
    for part in msg.walk():
        if part.get_content_type() != "message/delivery-status":
            continue
        raw = str(part)
        status = None
        m = re.search(r"Status:\s*([245]\.\d{1,3}\.\d{1,3})", raw, re.I)
        if m:
            status = m.group(1)
        rcpt = None
        r = re.search(r"Final-Recipient:\s*[^;]+;\s*<?([^>\s]+@[^>\s]+)>?", raw, re.I)
        if r:
            rcpt = r.group(1).lower()
        return status, rcpt
    return None, None


def classify(msg: Message) -> Classification:
    ev: list[str] = []
    subject = _h(msg, "Subject")
    sender = _h(msg, "From").lower()
    return_path = _h(msg, "Return-Path")
    auto_submitted = _h(msg, "Auto-Submitted").lower()
    precedence = _h(msg, "Precedence").lower()
    body = _body_text(msg)

    # ---- 1. Delivery reports. Structured, and the most consequential to get right.
    if _is_dsn(msg) or any(d in sender for d in _DAEMONS[:4]):
        status, rcpt = _dsn_status(msg)
        ev.append(f"DSN (status={status or 'unparsed'})")
        if status:
            hard = status.startswith("5")
        else:
            # No enhanced status: fall back to phrases, then to the raw SMTP code.
            if _HARD_PHRASES.search(body):
                hard, _ = True, ev.append("hard-failure phrase")
            elif _SOFT_PHRASES.search(body):
                hard, _ = False, ev.append("transient-failure phrase")
            else:
                codes = _SMTP_CODE.findall(body)
                hard = any(c.startswith("5") for c in codes)
                ev.append(f"smtp codes {codes[:3] or 'none'}")
        return Classification(
            kind=Kind.BOUNCE_HARD if hard else Kind.BOUNCE_SOFT,
            confidence=0.95 if status else 0.7, evidence=ev, bounced_address=rcpt)

    # ---- 2. Machine-generated, per the headers the sender actually set.
    # RFC 3834. "auto-replied" and "auto-generated" both mean: no human typed this.
    if auto_submitted and auto_submitted != "no":
        ev.append(f"Auto-Submitted: {auto_submitted}")
        kind = Kind.OUT_OF_OFFICE if _looks_ooo(subject, body) else Kind.AUTO_REPLY
        return Classification(kind=kind, confidence=0.95, evidence=ev)

    for header in ("X-Autoreply", "X-Autorespond", "X-Auto-Response-Suppress",
                   "X-Vacation-Message"):
        if msg.get(header):
            ev.append(f"{header} present")
            kind = Kind.OUT_OF_OFFICE if _looks_ooo(subject, body) else Kind.AUTO_REPLY
            return Classification(kind=kind, confidence=0.9, evidence=ev)

    if precedence in ("auto_reply", "bulk", "junk", "list"):
        ev.append(f"Precedence: {precedence}")
        return Classification(Kind.AUTO_REPLY, confidence=0.75, evidence=ev)

    # A null Return-Path means the sender does not want bounces back - i.e. it is not
    # a person writing to you. Checked after DSN so a bounce is classified as a bounce.
    if return_path in ("<>", ""):
        if return_path == "<>":
            ev.append("null Return-Path")
            kind = Kind.OUT_OF_OFFICE if _looks_ooo(subject, body) else Kind.AUTO_REPLY
            return Classification(kind=kind, confidence=0.8, evidence=ev)

    # ---- 3. Explicit opt-out beats intent analysis. Never argue with it.
    if _UNSUB.search(subject) or _UNSUB.search(body[:1500]):
        ev.append("opt-out language")
        return Classification(Kind.UNSUBSCRIBE, confidence=0.9, evidence=ev)

    # ---- 4. Subject-only OOO. Last resort: a person can type "Out of office" too,
    # so this is lower confidence and deliberately below every header check.
    if _looks_ooo(subject, body):
        ev.append("out-of-office wording (no supporting header)")
        return Classification(Kind.OUT_OF_OFFICE, confidence=0.6, evidence=ev)

    # ---- 5. A human wrote this. Now, and only now, guess at intent.
    return Classification(Kind.HUMAN_REPLY, intent=infer_intent(body),
                          confidence=0.8, evidence=ev or ["no machine markers"])


def infer_intent(body: str) -> Intent:
    """Cheap deterministic pass. Referral is checked before objection because
    'not the right person, speak to Dana' contains a negation but is a good outcome."""
    head = body[:2000]
    if _REFERRAL.search(head):
        return Intent.REFERRAL
    if _OBJECTION.search(head):
        return Intent.OBJECTION
    if _POSITIVE.search(head):
        return Intent.POSITIVE
    return Intent.NEUTRAL
